// src/components/StudioSpace.tsx
import React from 'react';
import { ImageWithFallback } from './figma/ImageWithFallback';

const images = [
  { image: './images/studio/4.jpg', title: 'Главный зал' },
  { image: './images/studio/2.jpg', title: 'Процедурная' },
  { image: './images/studio/3.jpg', title: 'Ресепшн' },
  { image: './images/studio/5.jpg', title: 'Зона отдыха' },
];

export default function StudioSpace() {
  return (
    <section className="py-32">
      <div className="container px-6 lg:px-12">
        <div className="max-w-3xl mb-20">
          <p className="label text-xs text-[#D81B60] mb-4">Пространство</p>
          <h2 className="display text-5xl lg:text-6xl text-[#1A1A1A] mb-6">
            Наша студия
          </h2>
          <p className="body text-lg text-[#424242]">
            Современное пространство, созданное для вашего комфорта и отдыха
          </p>
        </div>

        {/* Main Image */}
        <div className="aspect-[21/9] bg-[#F5F5F5] mb-8 overflow-hidden">
          <ImageWithFallback
            src="./images/studio/1.jpg"
            alt="Kamshuk Beauty Studio"
            className="w-full h-full object-cover"
          />
        </div>

        {/* Gallery */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {images.map((item, idx) => (
            <div key={idx} className="aspect-square bg-[#F5F5F5] overflow-hidden group">
              <ImageWithFallback
                src={item.image}
                alt={item.title}
                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
              />
            </div>
          ))}
        </div>

        {/* Address */}
        <div className="mt-20 text-center max-w-2xl mx-auto">
          <div className="bg-[#FAFAFA] px-12 py-10">
            <p className="headline text-2xl text-[#1A1A1A] mb-4">Адрес студии</p>
            <p className="body text-base text-[#424242] mb-6">
              г. Москва, Коммунарка<br />
              ул. Александры Монаховой д.43/1,<br /> здание SoiSoul, 1 этаж
            </p>
            <p className="label text-xs text-[#D81B60]">
              Ежедневно: 10:00 - 22:00
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

// components/StudioSpace.vue
<script setup lang="ts">
const images = [
  { image: '/images/studio/4.jpg', title: 'Главный зал' },
  { image: '/images/studio/2.jpg', title: 'Процедурная' },
  { image: '/images/studio/3.jpg', title: 'Ресепшн' },
  { image: '/images/studio/5.jpg', title: 'Зона отдыха' },
]
</script>

<template>
  <section class="py-28 bg-[#FFFCFA]">
    <div class="container px-6 lg:px-12">

      <!-- Заголовок -->
      <div class="flex flex-col lg:flex-row lg:items-end justify-between gap-8 mb-16">
        <div>
          <div class="section-label mb-5">Пространство</div>
          <h2 class="display text-4xl lg:text-5xl text-[#1A100C]">Наша студия</h2>
        </div>
        <p class="body text-base text-[#8A7A74] max-w-xs lg:text-right">
          Современное пространство, созданное для вашего комфорта и отдыха
        </p>
      </div>

      <!-- Главное фото -->
      <div class="relative aspect-[21/9] overflow-hidden rounded-3xl shadow-luxury mb-4">
        <img
          src="/images/studio/1.jpg"
          alt="Студия красоты Камшук Бьюти — главный зал"
          class="w-full h-full object-cover hover:scale-105 transition-transform duration-1000"
        />
        <div
          class="absolute inset-0 rounded-3xl"
          style="background: linear-gradient(to right, rgba(26,13,46,0.3) 0%, transparent 50%)"
        />
        <div class="absolute bottom-8 left-8">
          <p class="label text-[11px] text-[#C8A441] mb-1">Камшук Бьюти</p>
          <p class="headline text-2xl text-white">Студия красоты</p>
        </div>
      </div>

      <!-- Галерея -->
      <div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-16">
        <div
          v-for="(item, idx) in images"
          :key="idx"
          class="aspect-square overflow-hidden group rounded-2xl relative cursor-pointer"
        >
          <img
            :src="item.image"
            :alt="item.title"
            class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
          />
          <!-- Оверлей -->
          <div
            class="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-2xl"
            style="background: linear-gradient(to top, rgba(26,13,46,0.75) 0%, transparent 60%)"
          />
          <!-- Название -->
          <div class="absolute bottom-0 left-0 right-0 p-4 translate-y-2 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 transition-all duration-300">
            <span class="label text-[11px] text-[#C8A441] block mb-0.5">Студия</span>
            <span class="headline text-base text-white">{{ item.title }}</span>
          </div>
        </div>
      </div>

      <!-- Адрес -->
      <div class="max-w-2xl mx-auto">
        <div
          class="rounded-3xl p-8 lg:p-12 text-center"
          style="background: linear-gradient(135deg, rgba(200,164,65,0.08), rgba(126,207,222,0.08)); border: 1.5px solid rgba(200,164,65,0.2)"
        >
          <div class="text-4xl mb-6">📍</div>
          <p class="headline text-xl text-[#1A100C] mb-3">Адрес студии</p>
          <p class="body text-base text-[#5C4A44] mb-6 leading-relaxed">
            г. Москва, Коммунарка<br />
            ул. Александры Монаховой д. 43/1,<br />
            здание SoiSoul, 1 этаж
          </p>
          <div class="gold-divider mx-auto mb-5" />
          <p class="label text-[11px] text-[#C8A441]">Ежедневно: 10:00 — 22:00</p>
        </div>
      </div>

    </div>
  </section>
</template>
